						% This module replaces old shell/Makefile scripts.

-module(docgraphs_orangef).
-compile(export_all).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

-define(OUTPUT, "lib/pservices_orangef/doc").

run() ->
    %% Selfcare
    application:load(pservices),
    application:load(pserver),
    application:load(pservices_orangef),
    application:start(ucs),

    %% Selfcare Prod in Orangef
    %% Service Mobicarte
     landscape("file:/orangef/selfcare_long/promo_mobi.xml",
  	      [],
  	      [show_contents, show_links],
  	      "tree_promo_mobi.ps"),

     landscape("file:/orangef/selfcare_long/opt_jinf.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_opt_jinf.ps"),
     landscape("file:/orangef/selfcare_long/opt_sinf.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_opt_sinf.ps"),
     landscape("file:/orangef/selfcare_long/opt_weinf.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_opt_weinf.ps"),
     landscape("file:/orangef/selfcare_long/opt_europe.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_opt_europe.ps"),
     landscape("file:/orangef/selfcare_long/opt_maghreb.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_opt_maghreb.ps"),
     landscape("file:/orangef/selfcare_long/selfcare.xml#mainmenu",
 	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_mobi_menu.ps"),

     landscape("file:/orangef/home.xml##124",
   	      [ "file:/orangef/selfcare_long/recharge.xml",
   		"file:/orangef/selfcare_long/recharge_cmo.xml",
   		"file:/orangef/selfcare_long/selfcare_cmo.xml",
   		"file:/orangef/selfcare_long/selfcare.xml#mainmenu",
   		"file:/orangef/selfcare_long/selfcare_omer.xml#mainmenu",
   		"file:/orangef/selfcare_long/souscrire_options_cmo.xml",
  		"file:/orangef/selfcare_long/souscrire_options_cmo.xml"
  		"#weekend_success"],
   	      [show_contents,show_links],
   	      "tree_recharge_direct.ps"),

     landscape("file:/orangef/selfcare_long/nouveautes.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml",
 	       "file:/orangef/selfcare_long/plan_tarifaire.xml",
 	       "file:/orangef/selfcare_long/payasyougo.xml"],
  	      [show_contents, show_links],
  	      "tree_nouveautes.ps"),

     landscape("file:/orangef/selfcare_long/plan_tarifaire.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_contents, show_links],
  	      "tree_selfcare_long_plan.ps"),

     landscape("file:/orangef/selfcare_long/plan_tarifaire.xml",
  	      ["file:/orangef/selfcare_long/recharge.xml"],
  	      [show_links],
  	      "tree_selfcare_long_plan_link.ps"),

%%%RECHARGEMENT

    landscape("file:/orangef/selfcare_long/recharge_cb_mobi.xml",
     	      ["file:/orangef/selfcare_long/selfcare.xml#recharge"],
     	      [show_contents, show_links],
     	      "tree_recharge_mobi_cb.ps"),
    
    landscape("file:/orangef/selfcare_long/recharge.xml",
	      ["file:/orangef/selfcare_long/opt_weinf.xml#success",
	       "file:/orangef/selfcare_long/opt_europe.xml#success",
	       "file:/orangef/selfcare_long/opt_maghreb.xml#success",
	       "file:/orangef/selfcare_long/selfcare.xml#recharge",
	       "file:/orangef/selfcare_long/selfcare.xml#mainmenu"],
     	      [show_contents, show_links],
     	      "tree_recharge_mobi_tr.ps"),
    
    landscape("file:/orangef/selfcare_long/recharge_cmo.xml",
     	      ["file:/orangef/selfcare_long/souscrire_options_cmo.xml",
    	       "file:/orangef/selfcare_long/souscrire_options_cmo.xml#bon_plan",
    	       "file:/orangef/selfcare_long/souscrire_options_cmo.xml#weekend_success"],
     	      [show_contents, show_links],
     	      "tree_recharge_cmo_tr.ps"),
    
    landscape("file:/orangef/selfcare_long/recharge_cmo_tlr.xml",
   	      [ "file:/orangef/selfcare_long/recharge_cmo.xml",
   		"file:/orangef/selfcare_long/selfcare_cmo.xml",
   		"file:/orangef/selfcare_long/recharge_cmo_cb.xml",
  		"file:/orangef/selfcare_long/selfcare_cmo.xml#mainmenu",
   		"file:/orangef/selfcare_long/souscrire_options_cmo.xml",
		"file:/orangef/selfcare_long/selfcare_cmo.xml#recharge"],
   	      [show_links],
   	      "tree_recharge_cmo_tlr.ps"),
    
    landscape("file:/orangef/selfcare_long/recharge_cmo_cb.xml",
   	      [ "file:/orangef/selfcare_long/recharge_cmo.xml",
   		"file:/orangef/selfcare_long/selfcare_cmo.xml",
   		"file:/orangef/selfcare_long/recharge_cmo_tlr.xml",
  		"file:/orangef/selfcare_long/selfcare_cmo.xml#mainmenu",
   		"file:/orangef/selfcare_long/souscrire_options_cmo.xml"],
   	      [show_links],
   	      "tree_recharge_cmo_cb.ps"),
    
     %% Service CMO

     landscape("file:/orangef/selfcare_long/options_cmo.xml",
  	      ["file:/orangef/selfcare_long/souscrire_options_cmo.xml",
  	       "file:/orangef/selfcare_long/sms_infos.xml"],
  	      [show_contents, show_links],
  	      "tree_options_cmo.ps"),

     landscape("file:/orangef/selfcare_long/promo_cmo.xml",
  	      ["file:/orangef/selfcare_long/selfcare_cmo.xml"],
  	      [show_contents, show_links],
  	      "tree_promo_cmo.ps"), 

     landscape("file:/orangef/selfcare_long/souscrire_options_cmo.xml",
 	      ["file:/orangef/selfcare_long/selfcare_cmo.xml#recharge",
 	       "file:/orangef/selfcare_long/sms_infos.xml",
 	       "file:/orangef/selfcare_long/mmsinfos.xml",
 	       "file:/orangef/selfcare_long/orange_ligue1.xml",
 	       "file:/orangef/selfcare_long/recharge_cmo.xml"
 	       "file:/orangef/selfcare_long/recharge_cb_cmo.xml"],
 	      [show_contents, show_links],
 	      "tree_souscription_cmo.ps"),

    landscape("file:/mcel/acceptance/cmo/Home_page.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_home_page.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/media_decouvrt.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_media_decouvrt.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/media_internet.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_media_internet.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/media_internet_plus.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_media_internet_plus.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_1h_ts_reseaux.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_1h_ts_reseaux.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_2numpref.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_2numpref.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_3num_kdo.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_3num_kdo.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_3num_kdo_sms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_3num_kdo_sms.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_J_illi_Data.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_J_illi_Data.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_OW_10E.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_OW_10E.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_OW_30E.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_OW_30E.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_WE_OW.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_WE_OW.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_bons_plans.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_bons_plans.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_cadeau_orange_MMS.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_cadeau_orange_MMS.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_credit_OW_of.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_credit_OW_of.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_credit_sms_of.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_credit_sms_of.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_credit_voix_of.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_credit_voix_of.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_etudiante.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_etudiante.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_europe.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_europe.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_five_min.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_five_min.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_jinf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_jinf.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_m6_smsmms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_m6_smsmms.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_maghreb.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_maghreb.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_pass_vacances.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_pass_vacances.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_report.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_report.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_seminf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_seminf.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sinf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sinf.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sl_7E.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sl_7E.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_12.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_12.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_18.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_18.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_25.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_25.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_3.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_3.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_7_5.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_7_5.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_sms_quoti.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_sms_quoti.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_ssms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_ssms.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_tt_shuss_sms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_tt_shuss_sms.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_tt_shuss_voix.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_tt_shuss_voix.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_unik_fixe.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_unik_fixe.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_unik_orange_fixe.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_unik_orange_fixe.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_we_sms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_we_sms.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_we_voix.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_we_voix.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_weinf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_weinf.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/opt_weinf_OW_TV.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_opt_weinf_OW_TV.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/osl.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_osl.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/ow_musique.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_musique.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/ow_spo.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_spo.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/ow_surf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_surf.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/ow_tv.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_tv.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/ow_tv2.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_tv2.ps"),
    landscape("file:/mcel/acceptance/cmo/Mes_options/sms_opt_OW.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms_opt_OW.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/accueil_bons_plans.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_accueil_bons_plans.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/afterschool.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_afterschool.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/bon_plan_sms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_bon_plan_sms.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/heures_zap_vacances.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_heures_zap_vacances.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/journees_infinies.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_journees_infinies.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/option_duo_journee.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_option_duo_journee.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/option_europe.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_option_europe.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/option_maghreb.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_option_maghreb.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/option_mms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_option_mms.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/pass_vacances.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_pass_vacances.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/soirees_infinies.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_soirees_infinies.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/soirees_sms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_soirees_sms.ps"),
    landscape("file:/mcel/acceptance/cmo/bons_plans_tarifaires/week-end_infini.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_week-end_infini.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/accueil_rechargement.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_accueil_rechargement.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_access_code.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_access_code.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_create_access_code.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_create_access_code.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_debrayage_vcod_mcod.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_debrayage_vcod_mcod.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_modify_access_code.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_modify_access_code.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_refill.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_refill.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rech_cb_reinit_code.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rech_cb_reinit_code.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rechargement_par_mobicarte.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rechargement_par_mobicarte.ps"),
    landscape("file:/mcel/acceptance/cmo/rechargement/rechargement_par_prelevement.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_rechargement_par_prelevement.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/accueil_options_sms_mms.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_accueil_options_sms_mms.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/sms_30.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms30.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/sms_80.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms80.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/sms_130.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms130.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/sms_210.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms210.ps"),
    landscape("file:/mcel/acceptance/cmo/options_SMS_MMS/sms_300.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_sms300.ps"),

    landscape("file:/mcel/acceptance/cmo/options_multimedia/accueil_options_multimedia.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_accueil_options_multimedia.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/decouverte_multimedia.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_decouverte_multimedia.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/option_internet.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_option_internet.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_musique.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_musique.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_sport.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_sport.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_surf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_surf.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_tt_tv.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_tt_tv.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_tv.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_tv.ps"),
    landscape("file:/mcel/acceptance/cmo/options_multimedia/ow_tv_music_surf.xml",
	     [],
	     [show_contents, show_links,horizontal],
	     "tree_ow_tv_music_surf.ps"),

    %% Home.


     %% Selfcare Niv 2

     landscape("file:/orangef/selfcare_light/selfcare.xml",
  	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_selfcare_light.ps"),

     landscape("file:/orangef/selfcare_light/selfcare.xml",
  	      exclude_123_suite(),
  	      [show_links],
  	      "tree_selfcare_light_link.ps"),

     landscape("file:/orangef/selfcare_light/selfcare_cmo.xml",
  	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_selfcare_cmo_light.ps"),

     landscape("file:/orangef/selfcare_light/selfcare_cmo.xml",
  	      exclude_123_suite(),
  	      [show_links],
  	      "tree_selfcare_cmo_light_link.ps"),

     %% Selfcare long
     application:set_env(posmon, warning_text_long, true),
 %%% test if all page of selfcare is less long than 181 caracters
     landscape("file:/orangef/selfcare_long/selfcare.xml",
  	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_selfcare_long.ps"),

     landscape("file:/orangef/selfcare_long/selfcare.xml",
  	      exclude_123_suite(),
  	      [show_links],
  	      "tree_selfcare_long_link.ps"),

     landscape("file:/orangef/selfcare_long/selfcare_cmo.xml",
  	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_selfcare_cmo_long.ps"),

     landscape("file:/orangef/selfcare_long/selfcare_cmo.xml",
  	      exclude_123_suite(),
  	      [show_links],
  	      "tree_selfcare_cmo_long_link.ps"),

     landscape("file:/orangef/selfcare_long/selfcare_cmo.xml#mainmenu",
  	      exclude_123_suite(),
  	      [show_contents, show_links],
  	      "tree_selfcare_main_cmo_long.ps"),

     %% Selfcare Niv 3

     landscape("file:/orangef/selfcare_mini/selfcare.xml",
  	      [],
  	      [show_contents, show_links],
  	      "tree_selfcare_mini.ps"),
     application:set_env(posmon, warning_text_long, false),


 %%% OTHERS SERVICES OPEN IN PRODUCTION ORANGEF
     landscape("file:/orangef/msisdn_operator.xml",
  	      [],
  	      [show_links],
  	      "tree_msisdn_link.ps"),
     landscape("file:/orangef/msisdn_operator.xml",
  	      [],
  	      [show_contents,show_links],
  	      "tree_msisdn_full.ps"),

 %%%% Recharge-moi
     landscape("file:/orangef/recharge_moi.xml",
 	      ["file:/orangef/selfcare_long/selfcare.xml#recharge",
 	       "file:/orangef/selfcare_long/selfcare_cmo.xml#recharge",
 	       "file:/orangef/selfcare_long/recharge.xml"],
   	      [show_links, show_contents, show_errors, show_failures],
   	      "tree_recharge_moi.ps"),

 %%%% dme long
     landscape("file:/orangef/selfcare_long/dme.xml",
  	      [],
   	      [show_links, show_contents, show_errors, show_failures],
   	      "tree_long_dme.ps"),

 %%%% dme light
     landscape("file:/orangef/selfcare_light/dme.xml",
  	      [],
   	      [show_links, show_contents, show_errors, show_failures],
   	      "tree_light_dme.ps"),

 %%%% dme mini
     landscape("file:/orangef/selfcare_mini/dme.xml",
 	      [],
 	      [show_links, show_contents, show_errors, show_failures],
  	      "tree_mini_dme.ps"),


 %%%% WIFI
     landscape("file:/orangef/wifi.xml",
  	      [],
  	      [show_links, show_contents, show_errors, show_failures],
  	      "tree_wifi.ps"),

 %%%% sms_games
     landscape("file:/orangef/sms_games.xml",
 	      [],
  	      [show_links, show_contents, show_errors, show_failures],
  	      "tree_sms_games.ps"),

 %%%% call_me_back
     landscape("file:/orangef/call_me_back.xml",
 	      ["file:/orangef/selfcare_long/selfcare.xml#recharge",
 	       "file:/orangef/selfcare_long/selfcare_cmo.xml#recharge",
 	       "file:/orangef/selfcare_long/recharge.xml"],
 	      [show_links, show_contents, show_errors, show_failures],
 	      "tree_call_me_back.ps"),

     %%%% annuaire
      landscape("file:/orangef/annuaire.xml",
 	       [],
 	      [show_links, show_contents, show_errors, show_failures],
 	      "tree_annuaire.ps"),

     %% home in orangef
     landscape("file:/orangef/home.xml",
 	      exclude_all_service(),
 	      [show_links],
 	      "tree_home_full.ps"),  

    %% draw_tree sets 'draw_tree_errors' if it has printed errors.
    case get(draw_tree_errors) of
	true -> erlang:halt(1);
	_ -> erlang:halt(0)
    end.

subtree(URL, Name) ->
    portrait(URL, exclude(), [show_links], "tree_"++Name++".ps").

subtree_horizontal(URL, Name) ->
    portrait(URL, exclude(), [show_links,horizontal], "tree_"++Name++".ps").

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

exclude_sc() ->
    [ "file:/orangef/selfcare/mobile_gagnant.xml",
      "file:/orangef/selfcare/changer_mobile.xml",
      "file:/orangef/selfcare/bonus_orange.xml",
      "file:/orangef/selfcare/recharge_cmo.xml#menu_recharger"
     ].

exclude_home() ->
    [
     "file:/test/index.xml",
     "file:/system/bookmarks.xml",
     "file:/orangef/selfcare/selfcare.xml",
     "file:/orangef/selfcare/selfcare_cmo.xml",
     "file:/demos/MOD/testservice.xml",
     "file:/demos/menu_clcm/menu.xml",
     "file:/orangef/selfcare/recharge.xml#direct_access",
     "file:/orangef/selfcare/recharge_cmo.xml#direct_access",
     "file:/demos/MOD/test.xml",
     "file:/demos/mobistar/mobistar.xml"
    ].

exclude_all_service()->
    exclude_home()++ exclude_MOD()++ exclude() ++ exclude_sc() ++ 
	[ "file:/orangef/selfcare_light/selfcare.xml",
	  "file:/orangef/selfcare_light/selfcare_cmo.xml",
	  "file:/orangef/selfcare_mini/selfcare.xml",
	  "file:/orangef/selfcare_mini/selfcare_cmo.xml",
	  "file:/orangef/selfcare_long/selfcare.xml",
	  "file:/orangef/selfcare_long/selfcare_cmo.xml",
	  "file:/orangef/selfcare_long/selfcare_cmo_new.xml",
	  "file:/orangef/selfcare_light/dme.xml",
	  "file:/orangef/selfcare_mini/dme.xml",
	  "file:/orangef/selfcare_long/dme.xml",
	  "file:/orangef/sms_games.xml",
	  "file:/orangef/msisdn_operator.xml",
	  "file:/orangef/home.xml#direct_recharge",
	  "file:/system/profilage.xml",
	  "file:/orangef/home.xml##141",
	  "file:/orangef/home.xml##142",
	  "file:/demos/voeux.xml",
	  "file:/orangef/home.xml#143",
	  "file:/orangef/home.xml##144",
	  "file:/orangef/home.xml##145",
	  "file:/orangef/home.xml#*146",
	  "file:/orangef/home.xml#call_me",
	  "file:/orangef/home.xml##147",
	  "file:/orangef/home.xml##149",
	  "file:/orangef/home.xml#main"
	 ].

exclude_MOD() ->
    [
     "file:/orangef/selfcare/selfcare.xml#mainmenuwithback",
     "file:/orangef/selfcare/selfcare_cmo.xml",

     "file:/demos/MOD/prat_progtv.xml",
     "file:/demos/MOD/prat_meteo.xml",
     "file:/demos/MOD/prat_annu.xml",
     "file:/demos/MOD/prat_dico.xml",
     "file:/demos/MOD/fun_jeux_lab.xml",
     "file:/demos/MOD/test.xml#info",
     "file:/demos/MOD/test.xml#news",
     "file:/demos/MOD/fun_horo.xml",
     "file:/demos/MOD/fun_divers.xml",
     "file:/demos/MOD/fun_nokiasmart.xml",
     "file:/demos/MOD/fun_repondeur.xml",
     "file:/demos/MOD/mobi_guide.xml"
    ].

exclude_menu_clcm() ->
    [
     "file:/orangef/selfcare/selfcare.xml#mainmenuwithback",
     "file:/orangef/selfcare/selfcare.xml#main",
     "file:/orangef/selfcare/selfcare_cmo.xml",
     "file:/orangef/selfcare_light/selfcare.xml",
     "file:/orangef/selfcare_light/selfcare_cmo.xml",

     "file:/demos/menu_clcm/info_insolite.xml",
     "file:/demos/menu_clcm/news_odd.xml",
     "file:/demos/menu_clcm/menu.xml#menuactu",
     "file:/demos/menu_clcm/menu.xml#menunews",
     "file:/demos/menu_clcm/menu.xml#news_progtv",
     "file:/demos/menu_clcm/info_tv.xml",
     "file:/demos/menu_clcm/info_lesgens.xml",
     "file:/fun/jdr/jeuxrole.xml",
     "file:/fun/quiz.xml",
     "file:/demos/comm/chat0.xml",
     "file:/demos/finance/converter.xml",
     "file:/demos/menu_clcm/horo_horo.xml",
     "file:/demos/menu_clcm/horo_horo_en.xml",
     "file:/demos/menu_clcm/games_maze.xml",
     "file:/demos/menu_clcm/jeux_lab.xml",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#2000",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#1990",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#1980",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#1970",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#1960",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#latino",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#classical",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#movies",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#tv",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#anthem",
     "file:/demos/menu_clcm/phonefun_ringtones.xml#misc",
     "file:/demos/menu_clcm/phonefun_voicemail.xml#imitations",

     "file:/demos/MOD/prat_progtv.xml",
     "file:/demos/MOD/prat_meteo.xml",
     "file:/demos/MOD/prat_annu.xml",
     "file:/demos/MOD/prat_dico.xml",
     "file:/demos/MOD/fun_jeux_lab.xml",
     "file:/demos/MOD/test.xml#info",
     "file:/demos/MOD/test.xml#news",
     "file:/demos/MOD/fun_horo.xml",
     "file:/demos/MOD/fun_divers.xml",
     "file:/demos/MOD/fun_nokiasmart.xml",
     "file:/demos/MOD/fun_repondeur.xml",
     "file:/demos/MOD/mobi_guide.xml"
    ].

exclude() ->
    [
     "file:/fun/quiz.xml",
     "file:/fun/hangman.xml",
     "file:/fun/jdr/jeuxrole.xml",
     "file:/fun/citatpensebisc.xml",

     "file:/demos/comm/callme.xml",
     "file:/demos/comm/chat0.xml",
     "file:/fun/hangman.xml",
     "file:/fun/blagues.xml",

     "file:/demos/MOD/testservice.xml"
    ].

exclude_123_suite()->
    [ "file:/orangef/selfcare_long/selfcare_long.xml",
      "file:/orangef/o2o.xml",
      "file:/orangef/selfcare_long/nouveautes.xml",
      "file:/orangef/selfcare_long/recharge.xml",
      "file:/orangef/selfcare_long/recharge_cmo.xml",
      "file:/orangef/selfcare_long/plan_tarifaire_free.xml",
      "file:/orangef/chat.xml",
      "file:/orangef/sms_games.xml",
      "file:/orangef/selfcare_long/opt_ow_3E_mobi.xml",
      "file:/orangef/selfcare_long/opt_ow_6E_mobi.xml",
      "file:/orangef/selfcare_long/opt_ow_10E_mobi.xml",
      "file:/orangef/selfcare_long/opt_owunite.xml",
      "file:/orangef/selfcare_long/opt_numprefp.xml",
      "file:/orangef/selfcare_long/opt_jinf.xml",
      "file:/orangef/selfcare_long/opt_sinf.xml",
      "file:/orangef/selfcare_long/opt_weinf.xml",
      "file:/orangef/selfcare_long/opt_europe.xml",
      "file:/orangef/selfcare_long/opt_maghreb.xml",
      "file:/orangef/selfcare_long/opt_tt_shuss.xml",
      "file:/orangef/selfcare_long/opt_appelprixunique.xml",
      "file:/orangef/selfcare_long/opt_afterschool.xml",
      "file:/orangef/selfcare_long/opt_ssms.xml",
      "file:/orangef/selfcare_long/opt_vacances.xml",      
      "file:/orangef/selfcare_long/recharge_cb_mobi.xml",
      "file:/orangef/selfcare_long/sms_infos.xml",
      "file:/orangef/selfcare_long/mmsinfos.xml",
      "file:/orangef/selfcare_long/orange_ligue1.xml",
      "file:/orangef/selfcare_long/options_sms.xml",
      "file:/orangef/selfcare_long/promo_mobi.xml",
      "file:/orangef/selfcare_long/sv_options.xml",
      "file:/orangef/selfcare_long/callback.xml",
      "file:/orangef/carte_postpale.xml",
      "file:/orangef/prov.xml"
     ].


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

landscape(URL, Exclude, Options, PSFile) ->
    Root = "lib/pservices/priv/xml",
    Dot = "/tmp/tree.dot",
    draw_tree:draw(Root, URL, Dot, Exclude, Options),
    Cmd = io_lib:format("dot -Tps -Gsize=12,8 -Gorientation=landscape ~s "
			"> ~s/~s", [Dot,  ?OUTPUT, PSFile]),
    os:cmd(Cmd).

portrait(URL, Exclude, Options, PSFile) ->
    Root = "lib/pservices/priv/xml",
    Dot = "/tmp/tree.dot",
    draw_tree:draw(Root, URL, Dot, Exclude, Options),
    Cmd = io_lib:format("dot -Tps -Gsize=10,7 -Gorientation=portrait ~s "
			"> ~s/~s", [Dot,  ?OUTPUT, PSFile]),
    os:cmd(Cmd).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


