-module(fake_sms_mms_infos_smi).

-export([start/0, loop/1, stop/0,handle_request/2, decode_by_name/2,build_record/2]).
-define(registered_name, ?MODULE).

start() ->
    io:format("!! STARTING SMS MMS INFOS FAKE !! ~n"),
    stop(),
    timer:sleep(500),
    register(?registered_name, proc_lib:spawn(?MODULE, loop, [dict:new()])).

loop(Accounts) ->
    receive
	{init, Msisdn, Data} ->	
	    loop(dict:store(Msisdn, Data, Accounts));
	{Pid, Http_body} ->
	    io:fwrite(">>>>> request received: ~p~n", [Http_body]),
	    {New_accounts, Response} = response(Accounts, Http_body),
	    Pid ! {?registered_name, Response},
	    loop(New_accounts);
	Else-> 
	    io:fwrite("Else: ~p~n", [Else]);
	stop ->
	    bye
    end.

stop(undefined) ->
    pass;
stop(Pid) when is_pid(Pid) ->
    Pid ! stop.

stop() ->
    stop(whereis(?registered_name)).

init_customer(Msisdn, Data) when length(Msisdn) == 10 ->
   ?registered_name ! {init, Msisdn, Data}.

handle_request(Header, Body)->
    ?registered_name ! {self(), Body},
    {Http_code, Response_xml} =
	receive
	    {?registered_name, exception} ->
		{500, exception_xml()};
	    {?registered_name, Response} ->
		io:fwrite(">>>>> fake response: ~p~n", [soaplight:build_xml([], [], Response)]),
		{200, soaplight:build_xml([], [], Response)}
	end,
    {Http_code, "application/xml+soap", Response_xml}.
    
decode_by_name(Name,Text) -> {Name,Text}.
build_record(Name,Elements) -> {Name,Elements}.

response(Accounts, XmlBody) when is_list(XmlBody) ->
    io:fwrite(">>>>> decoded fake response received: ~p~n", [soaplight:decode_body(XmlBody,?registered_name)]),
    response(Accounts, soaplight:decode_body(XmlBody,?registered_name));

response(Accounts, {'SMIsouscription',[{idCanalSouscr,"50"},{msisdn,Msisdn}, {idOption,IdOption},{codeCompOption,CodeCompOption}]}) ->
    Elements = [{'SMIsouscriptionResponse',
 		 [{status, [], "90"}
		 ]}],
    {Accounts, Elements};
response(Accounts, {'SMIsouscription',[{idCanalSouscr,"50"}, {msisdn,Msisdn}, {idOption,IdOption},{codeCompOption,CodeCompOption}]}) ->
    Elements = [{'SMIsouscriptionResponse',
 		 [{status, [], "90"}
		 ]}],
    {Accounts, Elements};


response(Accounts, {'SMIsouscription',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{idOption,IdOption}, {codeCompOption,CodeCompOption}]}) ->
    Elements = [{'SMIsouscriptionResponse',
 		 [{status, [], "90"}
		 ]}],
    {Accounts, Elements};

response(Accounts, {'SMImodification',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{idOption,IdOption}, {codeCompOption,CodeCompOption}]}) ->
    Elements = [{'SMImodificationResponse',
 		 [{status, [], "90"}
		 ]}],
    {Accounts, Elements};


response(Accounts, {'SMIresiliation',[{idCanalHistoSouscr,_},
				      {msisdn, Msisdn},
				      {idCompOption,_}]}) ->
    Elements = [{'SMIresiliationResponse',
 		 [{status, [], "90"}]}],
    {Accounts, Elements};




%%%%

response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"SMS"}]}) 
when Msisdn=="33900000617"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
					   [{idOption,[],"20006"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"J"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Actualite"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"20004"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"J"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Actu generique"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30010"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"J"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS TV"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30020"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"M"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Horoscope"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30005"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"E"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Cine"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30025"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"PROMBASE"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Star"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"45005"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"E"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Loto"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  
					  {souscOption, [],
					   [{idOption,[],"45004"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"P"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS quinte"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30005"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"E"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Blagues"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  {souscOption, [],
					   [{idOption,[],"30090"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1300"},
					    {tarifHorsPromo,[],"2000"},
					    {renouvellement,[],"1100"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"E"},
					    {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Blagues"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {idCompOption,[],"68"},
					    {lidCompOption,[],"Ales"},
					    {codeCompOption,[],"71"},
					    {ordreComOption,[],"9"}]},
					  
					  {souscOption, [],
					   [{idOption,[],"30000"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1305"},
					    {tarifHorsPromo,[],"1105"},
					    {renouvellement,[],"0"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"DEGRESSIFMENS"},
					    {typeFacturationHorsPromo,[],"MENSUEL"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS Sport"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {dateSouscription,[],"2008-05-16+02:00"},
					    {idCompOption,[],"1"},
					    {lidCompOption,[],"Bélier"},
					    {codeCompOption,[],"1"},
					    {ordreComOption,[],"1"}]},
					  {souscOption, [],
					   [{idOption,[],"10011"},
					    {tarif,[],"1500"},
					    {idTarif,[],"1305"},
					    {tarifHorsPromo,[],"1105"},
					    {renouvellement,[],"0"},
					    {uniteRenouvellement,[],"M"},
					    {typeFacturation,[],"DEGRESSIFMENS"},
					    {typeFacturationHorsPromo,[],"MENSUEL"},
					    {ordre,[],"0"},
					    {libOption,[],"SMS meteo"},
					    {descOption,[],""},
					    {presOption,[],""},
					    {flagOptionSouscrite,[],"0"},
					    {dateSouscription,[],"2008-05-16+02:00"},
					    {idCompOption,[],"1"},
					    {lidCompOption,[],"Bélier"},
					    {codeCompOption,[],"1"},
					    {ordreComOption,[],"1"}]}

						  ]}
		 ]}],
    {Accounts, Elements};




response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"SMS"}]}) 
  when Msisdn=="33900000628"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], 
		   [{souscOption, [],
		     [{idOption,[],"20006"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actualite"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"20004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"PRO"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actu generique"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30010"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS TV"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30020"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"M"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Horoscope"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {idCompOption,[],"5"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"5"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Cine"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30025"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Star"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"45005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Loto"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"45004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS quinte"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30090"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"30000"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Sport"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]},
		    {souscOption, [],
		     [{idOption,[],"10011"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS meteo"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"4307"},
		      {ordreComOption,[],"1"}]}
		    
		   ]}
		 ]}],
    {Accounts, Elements};

%% Actualites nationale
response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"SMS"}]}) 
  when Msisdn=="33900000021"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], 
		   [{souscOption, [],
		     [{idOption,[],"20006"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actualite"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"00"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"20004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"PRO"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actu generique"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30010"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS TV"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30020"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"M"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Horoscope"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {idCompOption,[],"5"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"5"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Cine"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30025"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Star"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"45005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Loto"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},

		    {souscOption, [],
		     [{idOption,[],"45004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS quinte"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30090"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},

		    {souscOption, [],
		     [{idOption,[],"30000"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Sport"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]},
		    {souscOption, [],
		     [{idOption,[],"10011"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS meteo"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"1"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"4307"},
		      {ordreComOption,[],"1"}]}
		   ]}
		 ]}],
    {Accounts, Elements};

response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"SMS"}]}) 
 when Msisdn=="33900000965"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], 
		   [{souscOption, [],
		     [{idOption,[],"20006"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actualite"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"20004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"PRO"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actu generique"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30010"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS TV"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30020"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Horoscope"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Cine"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30025"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"M"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS People"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"45005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Loto"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"45004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS quinte"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30090"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"30000"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Sport"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]},
		    {souscOption, [],
		     [{idOption,[],"10011"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS meteo"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]}
		    
						  ]}
		 ]}],
    {Accounts, Elements};

response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"SMS"}]}) ->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], 
		   [{souscOption, [],
		     [{idOption,[],"20006"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actualite"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"20004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"PRO"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Actu generique"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30010"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"J"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS TV"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30020"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"M"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Horoscope"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Cine"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30025"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Star"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"45005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Loto"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"45004"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS quinte"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    {souscOption, [],
		     [{idOption,[],"30090"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1300"},
		      {tarifHorsPromo,[],"2000"},
		      {renouvellement,[],"1100"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"E"},
		      {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Blagues"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {idCompOption,[],"68"},
		      {lidCompOption,[],"Ales"},
		      {codeCompOption,[],"71"},
		      {ordreComOption,[],"9"}]},
		    
		    {souscOption, [],
		     [{idOption,[],"30000"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS Sport"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]},
		    {souscOption, [],
		     [{idOption,[],"10011"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"SMS meteo"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]}
		    
						  ]}
		 ]}],
    {Accounts, Elements};








response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSI"}]})
when Msisdn=="33900000617"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
						    [{idOption,[],"50140"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Actualite"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50900"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Coquin"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50141"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"PROMBASE"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS TV"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50120"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"M"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Horoscope"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"13"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50015"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Cine"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50142"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS people"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50020"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Humour"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						  
						   {souscOption, [],
						    [{idOption,[],"50130"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Ligue 1"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"0"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]},
						   {souscOption, [],
						    [{idOption,[],"50011"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS meteo"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"Bélier"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]}

						  ]}
		 ]}],
    {Accounts, Elements};



response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSI"}]})
 when Msisdn=="33900000628"-> 
  Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
						    [{idOption,[],"50140"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Actualite"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50900"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Coquin"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50141"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS TV"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50120"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"M"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Horoscope"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"8"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"7"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50150"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Cine"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50142"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS people"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50020"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Humour"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						  
						   {souscOption, [],
						    [{idOption,[],"50130"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Ligue 1"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"0"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]},
						   {souscOption, [],
						    [{idOption,[],"50111"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS meteo"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"Bélier"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]}

						  ]}
		 ]}],
    {Accounts, Elements};












response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSI"}]}) ->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
						    [{idOption,[],"50140"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Actualite"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50900"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Coquin"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50141"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS TV"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50120"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"M"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Horoscope"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"13"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50015"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Cine"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50142"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS people"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"50020"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"SMS Humour"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						  
						   {souscOption, [],
						    [{idOption,[],"50130"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS Ligue 1"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"0"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]},
						   {souscOption, [],
						    [{idOption,[],"50011"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1305"},
						     {tarifHorsPromo,[],"1105"},
						     {renouvellement,[],"0"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"DEGRESSIFMENS"},
						     {typeFacturationHorsPromo,[],"MENSUEL"},
						     {ordre,[],"0"},
						     {libOption,[],"MMS meteo"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {dateSouscription,[],"2008-05-16+02:00"},
						     {idCompOption,[],"1"},
						     {lidCompOption,[],"Bélier"},
						     {codeCompOption,[],"1"},
						     {ordreComOption,[],"1"}]}

						  ]}
		 ]}],
    {Accounts, Elements};












%% REPONSE PROMO
response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSV"}]}) 
when Msisdn=="33900000617"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
						    [{idOption,[],"54130"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],""},
						     {descOption,[],"Video Orange L1"},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"54900"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"Video Charme"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"54200"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"PROMBASE"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"Video Humour"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]}
						  ]}
		 ]}],
    {Accounts, Elements};



%% REPONSE OPT ACTIVE
response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSV"}]}) 
when Msisdn=="33900000628"->
    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
						    [{idOption,[],"54130"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"J"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],""},
						     {descOption,[],"Video Orange L1"},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"54900"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"E"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"Video Charme"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"1"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]},
						   {souscOption, [],
						    [{idOption,[],"54200"},
						     {tarif,[],"1500"},
						     {idTarif,[],"1300"},
						     {tarifHorsPromo,[],"2000"},
						     {renouvellement,[],"1100"},
						     {uniteRenouvellement,[],"M"},
						     {typeFacturation,[],"PROMBASE"},
						     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
						     {ordre,[],"0"},
						     {libOption,[],"Video Humour"},
						     {descOption,[],""},
						     {presOption,[],""},
						     {flagOptionSouscrite,[],"0"},
						     {idCompOption,[],"68"},
						     {lidCompOption,[],"Ales"},
						     {codeCompOption,[],"71"},
						     {ordreComOption,[],"9"}]}
						  ]}
		 ]}],
    {Accounts, Elements};

response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"MMSV"}]}) ->

    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], [{souscOption, [],
					    [{idOption,[],"54130"},
					     {tarif,[],"1500"},
					     {idTarif,[],"1300"},
					     {tarifHorsPromo,[],"2000"},
					     {renouvellement,[],"1100"},
					     {uniteRenouvellement,[],"M"},
					     {typeFacturation,[],"J"},
					     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					     {ordre,[],"0"},
					     {libOption,[],""},
					     {descOption,[],"Video Orange L1"},
					     {presOption,[],""},
					     {flagOptionSouscrite,[],"0"},
					     {idCompOption,[],"68"},
					     {lidCompOption,[],"Ales"},
					     {codeCompOption,[],"71"},
					     {ordreComOption,[],"9"}]},
					   {souscOption, [],
					    [{idOption,[],"54900"},
					     {tarif,[],"1500"},
					     {idTarif,[],"1300"},
					     {tarifHorsPromo,[],"2000"},
					     {renouvellement,[],"1100"},
					     {uniteRenouvellement,[],"M"},
					     {typeFacturation,[],"E"},
					     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					     {ordre,[],"0"},
					     {libOption,[],"Video Charme"},
					     {descOption,[],""},
					     {presOption,[],""},
					     {flagOptionSouscrite,[],"0"},
					     {idCompOption,[],"68"},
					     {lidCompOption,[],"Ales"},
					     {codeCompOption,[],"71"},
					     {ordreComOption,[],"9"}]},
					   {souscOption, [],
					    [{idOption,[],"54200"},
					     {tarif,[],"1500"},
					     {idTarif,[],"1300"},
					     {tarifHorsPromo,[],"2000"},
					     {renouvellement,[],"1100"},
					     {uniteRenouvellement,[],"M"},
					     {typeFacturation,[],"P"},
					     {typeFacturationHorsPromo,[],"DEGRESSIFMENS"},
					     {ordre,[],"0"},
					     {libOption,[],"Video Humour"},
					     {descOption,[],""},
					     {presOption,[],""},
					     {flagOptionSouscrite,[],"0"},
					     {idCompOption,[],"68"},
					     {lidCompOption,[],"Ales"},
					     {codeCompOption,[],"71"},
					     {ordreComOption,[],"9"}]}
					  ]}
		 ]}],
    {Accounts, Elements};



response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"OL1"}]}) ->

    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [],Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [], 
		   [ {souscOption, [],
		      [{idOption,[],"33005"},
		       {tarif,[],"1500"},
		       {idTarif,[],"1305"},
		       {tarifHorsPromo,[],"1105"},
		       {renouvellement,[],"0"},
		       {uniteRenouvellement,[],"M"},
		       {typeFacturation,[],"PROMBASE"},
		       {typeFacturationHorsPromo,[],"MENSUEL"},
		       {ordre,[],"0"},
		       {libOption,[],"Orange Ligue1"},
		       {descOption,[],""},
		       {presOption,[],""},
		       {flagOptionSouscrite,[],"0"},
		       {dateSouscription,[],"2008-05-16+02:00"},
		       {idCompOption,[],"1"},
		       {lidCompOption,[],"Belier"},
		       {codeCompOption,[],"1"},
		       {ordreComOption,[],"1"}]}

		    ]}
		 ]}],
    {Accounts, Elements};


response(Accounts, {'SMIlisteOptions',[{idCanalSouscr,"50"}, {msisdn,Msisdn},{groupe,"OL1"}]}) ->

    Elements = [{'SMIlisteOptionsResponse',
 		 [{msisdn, [], Msisdn},
		  {status, [], "90"},
		  {codeOffre, [],"ENT" },
		  {controleParental, [],"N" },
		  {codeTac, [],"123456798" },
		  {abonneConnu, [],"N" },
		  {classeImage, [],"2" },
		  {classeVideo, [],"6"}, 
		  {compatAlertVideo, [],"N"},
		  {nbOptionsSouscrites, [],"0" },
		  {suspEnvoiMms, [],"N"},
		  {listSouscrOption, [],
		   [{souscOption, [],
		     [{idOption,[],"33005"},
		      {tarif,[],"1500"},
		      {idTarif,[],"1305"},
		      {tarifHorsPromo,[],"1105"},
		      {renouvellement,[],"0"},
		      {uniteRenouvellement,[],"M"},
		      {typeFacturation,[],"DEGRESSIFMENS"},
		      {typeFacturationHorsPromo,[],"MENSUEL"},
		      {ordre,[],"0"},
		      {libOption,[],"Orange Ligue1"},
		      {descOption,[],""},
		      {presOption,[],""},
		      {flagOptionSouscrite,[],"0"},
		      {dateSouscription,[],"2008-05-16+02:00"},
		      {idCompOption,[],"1"},
		      {lidCompOption,[],"Bélier"},
		      {codeCompOption,[],"1"},
		      {ordreComOption,[],"1"}]}

		   ]}
		 ]}],
    {Accounts, Elements};


response(Accounts, Else) ->
    io:format("UNKNOWN REQUEST ~p ~n",[Else]),
    Elements = [{'SMISouscriptionResponse',
 		 [{status, [], "99"}
		 ]}],
    {Accounts, Elements}.

exception_xml() ->
    "".

current_date_string() ->
    {{Y,M,D}, _} = erlang:localtime(),
    lists:flatten(io_lib:fwrite("~2.2.0w/~2.2.0w/~w", [D, M, Y])).

current_time_string() ->
    {_, {H, Min, S}} = erlang:localtime(),
    lists:flatten(io_lib:fwrite("~2.2.0w:~2.2.0w:~2.2.0w", [H, Min, S])).
