echo test_activ_opt_cmo
make test_activ_opt_cmo
echo test_annuaire
make test_annuaire
echo test_bzh_cmo
make test_bzh_cmo
echo test_callback
make test_callback
echo test_call_me_back
make test_call_me_back
echo test_144_carrefour_pp
make test_144_carrefour_pp
echo test_chat
make test_chat
echo test_cmo
make test_cmo_compl
make test_cmo_compl
echo test_cmo
echo test_123_dme
make test_123_dme
echo test_fill_handsim
make test_fill_handsim
echo test_identifying_user_local
make test_identifying_user_local
echo test_123_m5
make test_123_m5
echo test_mmsinfos_locale
make test_mmsinfos_locale
echo test_mobi
make test_mobi
echo test_mobi_illimite_kdo
make test_mobi_illimite_kdo
echo test_mobi_aide
make test_mobi_aide
echo test_mobi_bons_plans
make test_mobi_bons_plans
echo test_mobi_bons_plans_vos_messages
make test_mobi_bons_plans_vos_messages
echo test_mobi_foot
make test_mobi_foot
echo test_mobi_fun
make test_mobi_fun
echo test_mobi_nouveautes
make test_mobi_nouveautes
echo test_mobi_refill
make test_mobi_refill
echo test_mobi_m6
make test_mobi_m6
echo test_mobi_unik
make test_mobi_unik

echo test_144_monacell_pp
make test_144_monacell_pp
echo test_144_monacell_cb
make test_144_monacell_cb
echo test_parentChild
make test_parentChild
echo test_plan_tarif_bzh_cmo
make test_plan_tarif_bzh_cmo
echo test_plan_tarif_mobi
make test_plan_tarif_mobi
echo test_plan_tarif_omer
make test_plan_tarif_omer
echo test_postpaid
make test_postpaid
echo test_promo_mobi
make test_promo_mobi
echo test_provisioning.hrl
test_provisioning_local
make test_provisioning_local
echo test_prov_selfcare_local
make test_prov_selfcare_local
echo test_recharge
echo test_recharge_cb_cmo_new
make test_recharge_cb_cmo_new
echo test_recharge_cb_mobi
make test_recharge_cb_mobi
echo test_recharge
echo test_recharge_moi
make test_recharge_moi
echo test_recharge_new
make test_recharge_new
echo test_roaming_cmo
make test_roaming_cmo
echo test_roaming_mobi
make test_roaming_mobi
echo test_roaming_postpaid
make test_roaming_postpaid
echo test_sachem
make test_sachem
echo test_script_xml
make test_script_xml
echo test_selfcare_cmo
make test_selfcare_cmo
echo test_selfcare_omer
make test_selfcare_omer
echo test_sms_games
make test_sms_games
echo test_smsinfo_locale
make test_smsinfo_locale
echo test_smspopup
make test_smspopup
echo test_spider
make test_spider
echo test_svc_limande
make test_svc_limande
echo test_svc_one2one
make test_svc_one2one
echo test_svc_wap_push_orangef
make test_svc_wap_push_orangef
echo test_sv_options_mobi
make test_sv_options_mobi
echo test_taxation_std_of
make test_taxation_std_of
echo test_tech_seg_utils
make test_tech_seg_utils
echo test_tele2_cb
make test_tele2_cb
echo test_tele2_pp
make test_tele2_pp
echo test_template
make test_template
echo test_144_ten_cb
make test_144_ten_cb
echo test_terminal_of
make test_terminal_of
echo test_transfert_credit
make test_transfert_credit
echo test_util_of
make test_util_of
echo test_util_spider
make test_util_spider
echo test_144_virgin_cb
make test_144_virgin_cb
echo test_virgin_pp
make test_virgin_pp
echo test_wifi
make test_wifi

echo test-activ_opt_cmo
make test-activ_opt_cmo
echo test-annuaire
make test-annuaire
echo test-bzh_cmo
make test-bzh_cmo
echo test-callback
make test-callback
echo test-call_me_back
make test-call_me_back
echo test-carrefour_pp
make test-carrefour_pp
echo test-chat
make test-chat
echo test-cmo
make test-cmo_compl
make test-cmo_compl
echo test-cmo
echo test-dme
make test-dme
echo test-fill_handsim
make test-fill_handsim
echo test-identifying_user_local
make test-identifying_user_local
echo test-m5
make test-m5
echo test-mmsinfos_locale
make test-mmsinfos_locale
echo test-mobi
make test-mobi
echo test-mobi_illimite_kdo
make test-mobi_illimite_kdo
echo test-mobi_illimite
make test-mobi_illimite
echo test-mobi_menus
make test-mobi_menus
echo test-mobi_aide
make test-mobi_aide
echo test-mobi_bons_plans
make test-mobi_bons_plans
echo test-mobi_bons_plans_vos_messages
make test-mobi_bons_plans_vos_messages
echo test-mobi_foot
make test-mobi_foot
echo test-mobi_fun
make test-mobi_fun
echo test-mobi_nouveautes
make test-mobi_nouveautes
echo test-mobi_refill
make test-mobi_refill
echo test-mobi_m6
make test-mobi_m6
echo test-mobi_unik
make test-mobi_unik
echo test-monacell
echo test-monacell
make test-monacell
echo test-options_mobi
make test-options_mobi
echo test-parentChild
make test-parentChild
echo test-plan_tarif_bzh_cmo
make test-plan_tarif_bzh_cmo
echo test-plan_tarif_mobi
make test-plan_tarif_mobi
echo test-plan_tarif_omer
make test-plan_tarif_omer
echo test-postpaid
make test-postpaid
echo test-promo_mobi
make test-promo_mobi
echo test-provisioning.hrl
test-provisioning_local
make test-provisioning_local
echo test-prov_selfcare_local
make test-prov_selfcare_local
echo test-recharge
make test-recharge_cb_cmo
make test-recharge_cb_cmo
echo test-recharge_cb_cmo_new
make test-recharge_cb_cmo_new
echo test-recharge_cb_mobi
make test-recharge_cb_mobi
echo test-recharge
echo test-recharge_moi
make test-recharge_moi
echo test-recharge_new
make test-recharge_new
echo test-roaming_cmo
make test-roaming_cmo
echo test-roaming_mobi
make test-roaming_mobi
echo test-roaming_postpaid
make test-roaming_postpaid
echo test-sachem
make test-sachem
echo test-script_xml
make test-script_xml
echo test-selfcare_cmo
make test-selfcare_cmo
echo test-selfcare_omer
make test-selfcare_omer
echo test-sms_games
make test-sms_games
echo test-smsinfo_locale
make test-smsinfo_locale
echo test-smspopup
make test-smspopup
echo test-spider
make test-spider
echo test-svc_limande
make test-svc_limande
echo test-svc_one2one
make test-svc_one2one
echo test-svc_wap_push_orangef
make test-svc_wap_push_orangef
echo test-sv_options_mobi
make test-sv_options_mobi
echo test-taxation_std_of
make test-taxation_std_of
echo test-tech_seg_utils
make test-tech_seg_utils
echo test-tele2_cb
make test-tele2_cb
echo test-tele2_pp
make test-tele2_pp
echo test-template
make test-template
echo test-ten_cb
make test-ten_cb
echo test-terminal_of
make test-terminal_of
echo test-transfert_credit
make test-transfert_credit
echo test-util_of
make test-util_of
echo test-util_spider
make test-util_spider
echo test-virgin_cb
make test-virgin_cb
echo test-virgin_pp
make test-virgin_pp
echo test-wifi
make test-wifi
echo test_svc_mipc
make test_svc_mipc
