include ../../../../../Makefile.defs

DOCS=		fs_annuaire
IMAGES=         annuaire_db annuaire_tech annuaire_tree
ASPELL_OPTS=	| aspell --master=french -H --encoding=utf-8 -l \

include $(TOPDIR)/make/docbook.mk


