include ../../../../../Makefile.defs

ERLPAS=	-pa $(TOPDIR)/possum/lib/pgsm/ebin	\
	-pa $(TOPDIR)/possum/lib/posutils/ebin \
	-pa $(TOPDIR)/possum/lib/xmerl/ebin \
	-pa $(TOPDIR)/possum/lib/xmlrpc/ebin \

include $(TOPDIR)/make/test.mk

