include ../../../../Makefile.defs

EBINAPPS=pfront_digital_print pgsm pfront pdist xmerl posutils ptester ucs\
         eva evae oma oma_tools oma_webmin pservices pserver posutils webuser\
        common_test_tools xmlrpc

include $(TOPDIR)/make/test.mk


export OMA_HOST = localhost
export OMA_PORT = 8080

export FIREFOX_BINARY = /usr/lib/firefox-2.0.0.14/firefox-bin
export WEBUSER_PORT=8081
export WEBUSER_HOST=localhost



online::online_all 
